### ISSUE TITLE
Links for installation or upgrade are broken

### ISSUE THREAD

**Issue by guldil** [punkave/symfony1#1]
Hi,

In readme the links for "Install Symfony and Doctrine" AND "Update Your Project, Symfony and Doctrine" are broken.

How can i install your fork in my existing project ?

Thanks

Guldil

**Comment by boutell** [comment]
These links are now fixed.

**Comment by boutell** [comment]
Whoops! Fixed these links. Thanks for reporting this.

On Fri, Apr 10, 2015 at 7:09 AM, guldil notifications@github.com wrote:

> Hi,
> 
> In readme the links for "Install Symfony and Doctrine" AND "Update Your
> Project, Symfony and Doctrine" are broken.
> 
> How can i install your fork in my existing project ?
> 
> Thanks
> 
> Guldil
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/symfony1/issues/1.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
